[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
nft_evo_tickets = "5MAXo56hQiQGL9hd9HJi9xdUnJNLXor3XYyK9kC4bNBn"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/nft-evo-tickets.ts"
