[toolchain]
anchor_version = "0.31.1"

[features]
resolution = true
skip-lint = false

[programs.devnet]
nft_evo_tickets = "6mz15gSnFGTWzjHsveE8aFpVTKjdiLkVfQKtvFf1CGdc"

[programs.localnet]
nft_evo_tickets = "6mz15gSnFGTWzjHsveE8aFpVTKjdiLkVfQKtvFf1CGdc"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/setup.ts tests/nft-evo-tickets.ts"

[test.validator]
url = "https://api.devnet.solana.com"

[[test.validator.clone]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
